language: objective-c
notifications:
  email: false
before_install:
  - brew update
  - brew outdated carthage || brew upgrade carthage
before_script:
  - carthage bootstrap --use-submodules --no-build
script: script/cibuild "$TRAVIS_XCODE_WORKSPACE" "$TRAVIS_XCODE_SCHEME" "$XCODE_ACTION"
xcode_workspace: Tentacle.xcworkspace
matrix:
  include:
    - xcode_scheme: Tentacle-OSX
      env: XCODE_ACTION=test
      osx_image: xcode7.3
    - xcode_scheme: Tentacle-iOS
      env: XCODE_ACTION=test
      osx_image: xcode7.3
    - xcode_scheme: update-test-fixtures
      env: XCODE_ACTION=build
      osx_image: xcode7.3
    - xcode_scheme: Tentacle-OSX
      env: XCODE_ACTION="build-for-testing test-without-building"
      osx_image: xcode8
    - xcode_scheme: Tentacle-iOS
      env: XCODE_ACTION="build-for-testing test-without-building"
      osx_image: xcode8
    - xcode_scheme: update-test-fixtures
      env: XCODE_ACTION=build
      osx_image: xcode8
