language: objective-c
notifications:
  email: false
osx_image: xcode7.3
before_install:
  - brew update
  - brew outdated carthage || brew upgrade carthage
before_script:
  - carthage bootstrap --use-submodules --no-build
script: script/cibuild "$TRAVIS_XCODE_WORKSPACE" "$TRAVIS_XCODE_SCHEME"
xcode_workspace: Tentacle.xcworkspace
xcode_scheme:
 - Tentacle-OSX
 - Tentacle-iOS
 - update-test-fixtures
