language: objective-c
notifications:
  email: false
branches:
  only:
    - master
before_script:
  - git submodule update --init --recursive
script: script/cibuild "$TRAVIS_XCODE_WORKSPACE" "$TRAVIS_XCODE_SCHEME" "$XCODE_ACTION"
xcode_workspace: Tentacle.xcworkspace
matrix:
  include:
    - xcode_scheme: Tentacle-OSX
      env: XCODE_ACTION="build-for-testing test-without-building"
      osx_image: xcode8.2
    - xcode_scheme: Tentacle-iOS
      env: XCODE_ACTION="build-for-testing test-without-building"
      osx_image: xcode8.2
    - xcode_scheme: update-test-fixtures
      env: XCODE_ACTION=build
      osx_image: xcode8.2
